name: Build flatpak

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"
      - "flatpak*"

jobs:
  build_flatpak:
    name: Build flatpak
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ua
          submodules: recursive

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build flatpak
        run: |
          ./docker/flatpak-build.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/flatpak')
        with:
          files: |
            ./ywallet.flatpak
            ./zwallet.tgz
            ./libwarp_api_ffi.so
